### ISSUE TITLE
Running multiple instances of nsntrace at one time

### ISSUE THREAD

**Issue by internaldefect** [nsntrace/nsntrace#21]
```
edit: doing research, probably gonna solve that in few upcoming days
edit2: research ended, wrote python script that does the job. I don't have time right now for that, maybe in future I will solve that problem
```
Hi,
Im trying to capture packets of few processes at the same time.
Currently, when I run nsntrace like that:
`user@host:~/nsntrace$ sudo ./src/nsntrace -d eth0 ping google.com`
It produces following output:
```
Starting network trace of 'ping' on interface eth0.
Your IP address in this trace is 172.16.42.255.
Use ctrl-c to end at any time.

PING google.com (216.58.209.206) 56(84) bytes of data.
64 bytes from bud02s22-in-f206.1e100.net (216.58.209.206): icmp_seq=1 ttl=55 time=14.4 ms
64 bytes from bud02s22-in-f206.1e100.net (216.58.209.206): icmp_seq=2 ttl=55 time=14.5 ms
[...]
```
When I execute same command in another terminal window (previous still running), it produces such output:
_(lines starting with [X] are added to code manually by myself, for debug purposes)_
```
[X] failed at _nsntrace_net_create_veth -> rtnl_link_veth_add
[X] failed at nsntrace_net_init -> _nsntrace_net_create_veth
Failed to setup networking environment
user@host:~/nsntrace$ 
```
And window that was properly pinging changes to:
```
[...]
64 bytes from bud02s22-in-f206.1e100.net (216.58.209.206): icmp_seq=4 ttl=55 time=14.7 ms
64 bytes from bud02s22-in-f206.1e100.net (216.58.209.206): icmp_seq=5 ttl=55 time=14.4 ms
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
ping: sendmsg: Network is unreachable
^C
--- google.com ping statistics ---
13 packets transmitted, 5 received, 61% packet loss, time 12060ms
Capture interrupted, cleaning up
Finished capturing 55 packets.
iptables: No chain/target/match by that name.
user@host:~/nsntrace$ 
```
That means that nsntrace was not designed to run in parallel. I want to modify it in such way, that it would work simultaneously.
As far, I changed defines:
```
#define IF_BASE "nsntrace"
#define NS_IF IF_BASE "-netns"
#define GW_IF IF_BASE
```
To variables, randomly generated at start of the program. Also replaced all occurances of GW_BASE  in the code to IF_BASE, as they have the same value. Without much reading of a code, I thought that would be the way of approaching what I wanted.
Now, clues lead to that part of code (net.c, 259 line in my setup):
```
_nsntrace_net_create_veth(const char *gw_iface,
			  const char *ns_iface,
			  pid_t ns_pid)
{
	int ret;
	struct nl_sock *sock = _nsntrace_net_get_nl_socket();

	if ((ret = rtnl_link_veth_add(sock, gw_iface, ns_iface, ns_pid)) < 0) {
		printf("failed at _nsntrace_net_create_veth -> rtnl_link_veth_add\n");
		return ret;
	}

	return 0;
}
```
Why that fails?
Why both of the instances fails? It looks like they fight with each other. They have something in common. Socket?
`_nsntrace_net_get_nl_socket()`
Uses:
`nl_socket_alloc()`
https://www.infradead.org/~tgr/libnl/doc/api/group__socket.html#gaf9458e6b88324962065f93a13d53cf2c
If I'm thinking right... that should create **new** socket? So why it interferes with each other?

So, final question:
Dear community, dear author: what else should I do in order to run multiple instances of nsntrace?
P.s.: Also tried to change (because that pair of IPs should be unique for each session too. Right?)
`#define GW_IP IP_BASE ".254"`
to
`#define GW_IP IP_BASE ".253"`
But that doesn't work at all:
_(Same result whe4n changed NS_IP.)_
```
user@host:~/nsntrace$ sudo ./src/nsntrace -d eth0 ping google.com
[sudo] password for user: 
Starting network trace of 'ping' on interface eth0.
Your IP address in this trace is 172.16.42.255.
Use ctrl-c to end at any time.

ping: unknown host google.com
Finished capturing 28 packets.
user@host:~/nsntrace$ 
```

**Comment by jonasdn** [comment]
Hi!

Thanks for reporting this issue! And for the work you put down! You were definitely on the right track!

In order to run multiple instances of nsntrace we need to make sure that the interface names does not clash with each other. And we need to make sure that we do not get any IP address clashes!

I have put together a pull-request that works fairly reliably for me. It still has some potential race conditions when launching multiple instances very fast. Since the information about which IP addresses that are bound might not have had time to update.

The PR can be found here: #36 

Thanks again!
